// Generated by gencpp from file occ_predictor_msgs/PredictPCL.msg
// DO NOT EDIT!


#ifndef OCC_PREDICTOR_MSGS_MESSAGE_PREDICTPCL_H
#define OCC_PREDICTOR_MSGS_MESSAGE_PREDICTPCL_H

#include <ros/service_traits.h>


#include <occ_predictor_msgs/PredictPCLRequest.h>
#include <occ_predictor_msgs/PredictPCLResponse.h>


namespace occ_predictor_msgs
{

struct PredictPCL
{

typedef PredictPCLRequest Request;
typedef PredictPCLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredictPCL
} // namespace occ_predictor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::occ_predictor_msgs::PredictPCL > {
  static const char* value()
  {
    return "1d63e5eadaf190a0779142cc5f3ada89";
  }

  static const char* value(const ::occ_predictor_msgs::PredictPCL&) { return value(); }
};

template<>
struct DataType< ::occ_predictor_msgs::PredictPCL > {
  static const char* value()
  {
    return "occ_predictor_msgs/PredictPCL";
  }

  static const char* value(const ::occ_predictor_msgs::PredictPCL&) { return value(); }
};


// service_traits::MD5Sum< ::occ_predictor_msgs::PredictPCLRequest> should match
// service_traits::MD5Sum< ::occ_predictor_msgs::PredictPCL >
template<>
struct MD5Sum< ::occ_predictor_msgs::PredictPCLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::occ_predictor_msgs::PredictPCL >::value();
  }
  static const char* value(const ::occ_predictor_msgs::PredictPCLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::occ_predictor_msgs::PredictPCLRequest> should match
// service_traits::DataType< ::occ_predictor_msgs::PredictPCL >
template<>
struct DataType< ::occ_predictor_msgs::PredictPCLRequest>
{
  static const char* value()
  {
    return DataType< ::occ_predictor_msgs::PredictPCL >::value();
  }
  static const char* value(const ::occ_predictor_msgs::PredictPCLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::occ_predictor_msgs::PredictPCLResponse> should match
// service_traits::MD5Sum< ::occ_predictor_msgs::PredictPCL >
template<>
struct MD5Sum< ::occ_predictor_msgs::PredictPCLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::occ_predictor_msgs::PredictPCL >::value();
  }
  static const char* value(const ::occ_predictor_msgs::PredictPCLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::occ_predictor_msgs::PredictPCLResponse> should match
// service_traits::DataType< ::occ_predictor_msgs::PredictPCL >
template<>
struct DataType< ::occ_predictor_msgs::PredictPCLResponse>
{
  static const char* value()
  {
    return DataType< ::occ_predictor_msgs::PredictPCL >::value();
  }
  static const char* value(const ::occ_predictor_msgs::PredictPCLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OCC_PREDICTOR_MSGS_MESSAGE_PREDICTPCL_H
